name: tests
on:
  push:
    branches:
      - master
  pull_request:

env:
  GO_VERSION: 1.14

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: set up go ${{env.GO_VERSION}}
        uses: actions/setup-go@v1
        with:
          go-version: ${{env.GO_VERSION}}
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Go mod cache setup
        uses: actions/cache@v2
        with:
          path: ${{env.GOPATH}}/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build
        run: make all
  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/tsovak/go-test-parser/go
    steps:
      - name: set up go ${{env.GO_VERSION}}
        uses: actions/setup-go@v1
        id: go
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Check out code into the Go module directory
        uses: actions/checkout@master
        with:
          path: go/src/github.com/tsovak/go-test-parser
          fetch-depth: 1
      - name: Go mod cache setup
        uses: actions/cache@v2
        with:
          path: ${{env.GOPATH}}/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test
        run: make mod unit
        working-directory: ${{env.GOPATH}}/src/github.com/tsovak/go-test-parser
  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/tsovak/go-test-parser/go
    steps:
      - name: set up go ${{env.GO_VERSION}}
        uses: actions/setup-go@v1
        id: go
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Check out code into the Go module directory
        uses: actions/checkout@master
        with:
          path: go/src/github.com/tsovak/go-test-parser
          fetch-depth: 1
      - name: Add bin to path
        run: echo "::add-path::${{env.GOPATH}}/bin"
      - name: Install golangci
        run: make all golangci
        working-directory: ${{env.GOPATH}}/src/github.com/tsovak/go-test-parser
      - name: Run golangci-lint
        run: make lint
        working-directory: ${{env.GOPATH}}/src/github.com/tsovak/go-test-parser
