name: tests
on:
  push:
    branches:
      - master
  pull_request:

env:
  GO_VERSION: 1.14

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: set up go ${{env.GO_VERSION}}
        uses: actions/setup-go@v1
        with:
          go-version: ${{env.GO_VERSION}}
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Go mod cache setup
        uses: actions/cache@v2
        with:
          path: ${{env.GOPATH}}/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build
        run: make all
  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: set up go ${{env.GO_VERSION}}
        uses: actions/setup-go@v1
        with:
          go-version: ${{env.GO_VERSION}}
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Go mod cache setup
        uses: actions/cache@v2
        with:
          path: ${{env.GOPATH}}/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Make mod
        run: make mod
      - name: Test
        run: make unit-ci | tee test.log
      - name: Generate report
        run: |
          make build
          ./bin/go-test-parser -v -s -o report test.log
      - uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: report

  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: set up go ${{env.GO_VERSION}}
        uses: actions/setup-go@v1
        with:
          go-version: ${{env.GO_VERSION}}
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Go mod cache setup
        uses: actions/cache@v2
        with:
          path: ${{env.GOPATH}}/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run golangci-lint
        run: make lint